version: '3'

volumes:
  postgres_data:
    driver: local
    
services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
	  - KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 02091945@Rr++
      DB_VENDOR: POSTGRES
      DB_ADDR: dbpostgresqlbrsmeddistauthzn.postgres.database.azure.com
      DB_DATABASE: keycloak
      DB_USER: dbpostgresqlbrsmeddistauthzn
      DB_SCHEMA: public
      DB_PASSWORD: 02091945@Rr++
      KC_LOG_LEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443